export const GET_MOBILEDATA_REQUEST = "GET_MOBILEDATA_REQUEST";
export const GET_MOBILEDATA_SUCCESS = "GET_MOBILEDATA_SUCCESS";
export const GET_MOBILEDATA_FAILURE = "GET_MOBILEDATA_FAILURE";


export const GET_CARDATA_REQUEST = "GET_CARDATA_REQUEST";
export const GET_CARDATA_SUCCESS = "GET_CARDATA_SUCCESS";
export const GET_CARDATA_FAILURE = "GET_CARDATA_FAILURE";


export const GET_BIKEDATA_REQUEST = "GET_BIKEDATA_REQUEST";
export const GET_BIKEDATA_SUCCESS = "GET_BIKEDATA_SUCCESS";
export const GET_BIKEDATA_FAILURE = "GET_BIKEDATA_FAILURE";
